import type { Metadata } from "next"
import "./globals.css"
import { Providers } from "./api/auth/providers"
import ReduxProvider from './providers';

export const metadata: Metadata = {
  title: "Project Progress Follow Up - Computer Engineering",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <ReduxProvider>
            {children}
          </ReduxProvider>
        </Providers>
      </body>
    </html>
  )
}
